### ISSUE TITLE
RSS feed not work as expected

### ISSUE THREAD

**Issue by ysupr** [nfarina/feeds#27] opened 2015-10-29 13:08 UTC
Feeds latest version on el capitano, whenever i tried to add RSS account on feeds, it can pull and make notifications as usual, but when i hover the list, *it doesn't show popup preview like the others*.

And whenever i click the list of RSS feeds, *its not redirect to the link of RSS*.

you can check with [hackernews feeds](http://news.ycombinator.com/rss)

**Comment by nfarina** [comment] 2015-10-29 17:40
Hello, I'm running El Cap but I can't reproduce these issues - popovers work fine and clicking items works fine too - are you sure you're running the latest version from feedsapp.com?

**Comment by ysupr** [comment] 2015-10-29 22:17
mm its strange, when i click check for updates it says that i am using 2.1.1 and it was the latest ones.  
  
i think i will reinstall it, maybe it helps

**Comment by spambus** [comment] 2015-11-27 01:10
I have the same problem in 10.11.1 on both the app from feedsapp.com and also if I compile it myself with Xcode, when I hover over a news feed title, the menubar menu just closes.

I also get some compile errors on El Capitan in Xcode:

in AppDelegate.m line 88:     webView.policyDelegate = self;

gives error:AppDelegate.m:88:28: Assigning to 'id<WebPolicyDelegate>' from incompatible type 'AppDelegate *const __strong'

@line 130: if (notification) [self userNotificationCenter:nil didActivateNotification:notification];

gives error: Null passed to a callee that requires a non-null argument

I think this can be fixed with: [self userNotificationCenter:[NSUserNotificationCenter defaultUserNotificationCenter] didActivateNotification:notification];

Also because of new security measures in El Capitan, you need to add to the Info.plist 2 new keys in order to allow ougtoing unsecure connections to "http" feeds, otherwise you can't read feeds and you get errors in console about this.

1 dictionary key: App Transport Security Settings
1 boolean key: Allow Arbitrary Loads: YES

If you are interested:

I also created some code to display new feed items on LG TV's with WebOS as a Toast message directly on the TV. this works on all LG TV's with WebOS, the 2014 and later models...

I can also fix that when you select: Hide dock icon, you don't need to restart the app.

But could you fix the compile errors on El Capitan, I find it verry time consuming to debug code I have not written myself.

**Comment by andrewduck** [comment] 2015-12-15 07:13
I'm seeing the same problem with RSS feeds, with hovers not working and the menu bar collapsing immediately instead of showing the preview.

**Closed** 2015-12-16 17:48 UTC

**Comment by andrewduck** [comment] 2015-12-28 04:17
Can you build a new release with this fixed? Would be much appreciated.
